## To secure VM networking, we should:
# - Limit open ports (with Uncomplicated Firewall)
# - Rate-limit incoming network traffic (with fail2ban)

- name: Install secure networking dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - ufw
    - fail2ban

- name: Set secure default firewall policy
  ufw: policy=deny

- name: Allow SSH traffic
  ufw: rule=allow port=ssh

- name: Disable SSH passwords
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"

- name: Disable SSH challenge-response
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^ChallengeResponseAuthentication'
    line: "ChallengeResponseAuthentication no"

- name: Allow TCP on default HTTP port (80)
  ufw: rule=allow port=80 proto=tcp

- name: Ensure firewall is running
  ufw: state=enabled

- name: Ensure fail2ban is running
  service: name=fail2ban service=started