---
- hosts: workers
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - name: "[workers] Leave current Docker Swarm"
      shell: "docker swarm leave"
      register: swarm_leave

    - debug: msg="{{ swarm_leave.stdout }}"