---
- hosts: manager
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - include_tasks: ../tasks/setup_secure_networking.yml
    - include_tasks: ../tasks/setup_docker.yml
    - include_tasks: ../tasks/setup_docker_networking.yml
    - name: Open Docker Swarm management port
      ufw: rule=allow port=2377 proto=tcp

- import_playbook: ./start_swarm.yml
